# Copyright 2010 - 2011, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')
import os

# Linux specific flags
env.Append(CPPDEFINES=['QCC_OS_LINUX'])
env.Append(CPPDEFINES=['_GLIBCXX_USE_C99_FP_MACROS_DYNAMIC'])

env.Append(CFLAGS=['-Wall',
                   '-Werror=non-virtual-dtor',
                   '-pipe',
                   '-std=c99',
                   '-fno-strict-aliasing',
                   '-Wno-long-long'])

env.Append(CXXFLAGS=['-Wall',
                     '-Werror=non-virtual-dtor',
                     '-pipe',
                     '-std=gnu++0x',
                     '-fno-rtti',
                     '-fno-exceptions',
                     '-fno-strict-aliasing',
                     '-Wno-long-long',
                     '-Wno-deprecated'])


# Debug/Release Variants
if env['VARIANT'] == 'debug':
   env.Append(CFLAGS='-g')
   env.Append(CXXFLAGS='-g')
   env.Append(JAVACFLAGS='-g -Xlint -Xlint:-serial')
else:
   env.Append(CFLAGS='-Os')
   env.Append(CXXFLAGS='-Os')
   env.Append(LINKFLAGS='-s')
   env.Append(JAVACFLAGS='-Xlint -Xlint:-serial')
   env.MergeFlags('-fvisibility=hidden -fvisibility-inlines-hidden')
   env.MergeFlags('-fno-asynchronous-unwind-tables -fno-unwind-tables')
   env.MergeFlags('-ffunction-sections -fdata-sections -Wl,--gc-sections')
