# Copyright 2010 - 2011, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')
import os

# Import common Linux setttings
env.SConscript(['../SConscript'])

# Linux specific flags
env.Append(CPPDEFINES=['QCC_CPU_ARM'])
env.Append(CPPFLAGS=['-march=armv6',
                     '-mthumb-interwork'])

# Use the OpenEmbedded cross-compilation environment
vars = Variables()
vars.Add(PathVariable('OE_BASE', 'Base directory of OpenEmbedded build for ARM', os.environ.get('OE_BASE')))
vars.Update(env)
Help(vars.GenerateHelpText(env))

if '' == env.subst('$OE_BASE'):
   print 'OE_BASE variable is required for Linux/ARM builds'
   Exit()

# Use OpenEmbedded tools
gcc_prefix  = '$OE_BASE/bin/arm-angstrom-linux-gnueabi-'
env['CC']   = gcc_prefix + 'gcc'
env['CXX']  = gcc_prefix + 'g++'
env['LINK'] = gcc_prefix + 'gcc'




